### ISSUE TITLE
`ladder` config should be nested under `cpa.config`

### ISSUE THREAD

**Issue by pat-s** [codecentric/cluster-overprovisioner#14]
Otherwise it does not have an effect.
Currently, this chart places the config under `/`

https://github.com/codecentric/cluster-overprovisioner/blob/1e6ac5549c3919a22aa08b964be40e0671e6a2ee/charts/cluster-overprovisioner/values.yaml#L143-L152

but it should be 

```yml
cpa:
  config:
    ladder:
       [...]
```

**EDIT: I was wrong, it works as expected**
